# Generated by Django 6.1.1 on 2026-09-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('oab', models.CharField(max_length=20, unique=True, verbose_name='Número da OAB')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advogado',
                'verbose_name_plural': 'Advogados',
                'db_table': 'advogados',
                'ordering': ['nome'],
            },
        ),
    ]
